# Generated by Django 2.1.7 on 2019-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='power_type',
            new_name='energy_type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='power',
            new_name='wh_per_unit',
        ),
        migrations.AddField(
            model_name='item',
            name='default_usage',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
